<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head> 
      $! meta tag seems to screw things up in t3, but removing it in base.st doesn't fix tutorial pages !$
      $! <meta http-equiv="content-type" content="text/html; charset=utf-8" /> !$
      <title> Real World HAppS: The Cabalized, Self-Demoing HAppS Tutorial </title>
      <link rel="stylesheet" href="/static/tutorial.css" type="text/css" />
    </head> 

    <body>
      $ foreignchars() $
    </body>
</html> 

