<h4>Getting started with HAppS</h4>

<p>If you use Ruby on Rails, Django, Perl Catalyst, PHP, or some other popular web framework, but
have programmed in haskell and would like to use the world's greatest language for your next web project,
just keep reading. I promise by the time you're done you  will give you all the knowledge you need.</p>

<p>This tutorial is its own demo. Both the job board part, and the text you are reading this moment.
For best results, you should
<a href="/tutorial/run-tutorial-locally">install and run</a>
it in a local environment where you have control. Then, when you are done
learning, you can use the tutorial code as a starting point for your own
HAppS applications. 
</p>

<p>I'm going to repeat myself now. The best way to learn how to use use HAppS with this tutorial is to <a
href="/tutorial/run-tutorial-locally">install and run</a> it in a
local environment.  So if you can, do that first.

$!
<p>Getting on with the tutorial proper, our first lesson examines the 
<a href="/tutorial/main-function">main function</a> in a HAppS program.
The second lesson explains how to do <a
href="/tutorial/basic-url-handling">basic url handling</a>.
The third lesson covers <a href="/tutorial/templates-dont-repeat-yourself">using templates</a>.</p>


<p>All the lessons can be seen in the left panel.
Lessons that are planned but haven't been written yet are grayed out. 
</p>
!$
<p><a href="/tutorial/prerequisites">Installation prerequisites</a></p>