

<p>*********** My least favorite animal is $ leastFavoriteAnimal $. 

<p>*********** (set in another template, leastFavoriteAnimal.st) 

<p>*********** Notice that this template file uses CamelCase rather than dashes to separate words.
   Otherwise there's an error with included templates.
   So, in general: avoid template file names with dashes or underscores, and just use CamelCase for templates.
   Numbers are also not allowed.

<br>Try uncommenting the next line and see what you get:
  $! <p>Include least-favorite-animal.st: $ least-favorite-animal.st $ !$

