<h3>Populate your job board with dummy data</h3>

<p>Assumng you are following along with the tutorial and running locally, you now have a job board with one user
   ("testuser") and no jobs,  unless you took the time to create additional test data manually.

<p>
When quickly hacking together a data-driven website, populating your app with dummy data is a chore you
want to avoid wasting time on, so let's see how to do that. 

<p>Firstly, restart HAppS in a pristine state by either deleting or backing up your _local data directory
   as described earler.

<p>Now, click <a href="/tutorial/initializedummydata">this link</a>.

<p>If everything worked right, you should now have two <a href="/tutorial/consultants">users</a> and a
   couple hundred <a href="/tutorial/jobs">jobs</a> worth of test data
   displaying in your jobs site.

<p><a href="/tutorial/macid-updates-and-queries">What just happened?</a>

