<h3>The missing HAppS documentation, and what to do about it</h3>

<p>Unfortunately, the documentation for HAppS is
<a href="http://forums.somethingawful.com/showthread.php?threadid=2947408">cringeworthy</a>.
So  bad that honestly I wouldn't know where to start to fix it.
</p>

<p>
Instead of tackling the documentation probablem directly by doing the obvious thing
and writing patches for haddock, I decided to create an easy-to-install demo project
that included clear step-by-step instructions for getting from zero to final product. I figure what the HAppS
ecosystem needs most, after better documentation, is the opportunity for developers to make real money
doing real work by leveraging this technology. So the demo project is a job board.
It's full of dummy data at the moment, but feel free to post real jobs here if you have them on offer.

$!
Somewhat to my shame, I still haven't learned how HAppS data migrations work,
so every time I release a new version of the tutorial I lose all data -- however, if any real seeming jobs
get posted, I will make sure this doesn't happen. A good explanation of HAppS data migration is my top priority
for the next version anyway. !$


$! There is a real job board, based on code from this tutorial, at <a href="http://www.fpjobs.com">fpjobs.com</a>. !$

<p>
By the way,
<a href="/tutorial/viewprofile?user=tphyahoo">I am currently available for haskell, HAppS, and startup consulting</a>. 
</p>

<p>
My hope is that that this material will tempt people to try HAppS out.
Both curious developers, and investors that want a non-trivial website and are willing to
<a href="http://www.paulgraham.com/avg.html">gamble</a> on a new technology
if it can get the job better, and most importantly, faster.
With enough users, I believe the documentation and other "batteries not included" issues with
HAppS will matter less and less, as the gaps get plugged in a gradual way.

$!
I created this project, the Real 
World HAppS Tutorial, to popularize the use of haskell, with HAppS, in web applications. 
!$
</p> 

<p><a href="/tutorial/getting-started">Let's get started.</a></p>

