  My favorite animal is a: $ favoriteAnimal $ (set with setAttribute)
  <p>
  $ leastFavoriteAnimal() $
  <p>
  If I forget to set an attribute (favoriteMammal), it just doesn't display: $ favoriteMammal $

  <p>This is what happens when an include fails: $ nonexistingTemplate() $

  <p>The next bit includes a template from a template that is already an included template.</p>
  $ favoritePlant() $

  <p>
  You can comment out parts of a template: $! This Won't Display !$
  <p>You can display lists: $ favoriteMinerals $


  

