<h3>Prerequisites</h3>

<p>For best results with this tutorial, you hopefully have the following.</p>

<ul>
  <li>Basic knowledge of haskell and html.</li>
  <li>A somewhat modern computer. I have a PIII laptop with 512M of ram. </li>
  <li>A modern operating system. You should be able to develop HAppS applications using windows, mac, or linux.
        <ul>
	  <li>Linux Notes: I work with the latest <a href="http://www.ubuntu.com">ubuntu</a> linux distribution,
	  which is currently hardy heron. Works for HAppS pretty much out of the box </li>
	  <li>Win32 Notes: <a href="http://groups.google.com/group/fa.haskell/browse_thread/thread/e1f1d3bc65074b9c">
	                      You may have to darcs get HAppS-State head, and/or tweak the cabal file.</a> 
	  </li>
 	</ul>
      
  <li>If you want to create a public web site based on the materials here, I recommend getting either a private server (more expensive) or a virtual private server (less expensive) which gives you admin privileges to install the packages and software you need. I use the cheapest virtual private server plan at <a href="http://www.linode.com">linode</a> to host this tutorial publicly. I wouldn't try hosting a HappS project publicly using a shared hoster like <a href="http://www.dreamhost.com">dreamhost</a> that doesn't give you root powers to administer your server. (Dreamhost is great for other things, like cheap storage for online images.)</li>
  <li>More requirements are described in the instructions for
      <a href="/tutorial/run-tutorial-locally">installing and running this tutorial locally</a>.
      However, if you have the basics ingredients above you should be okay.
   </li>
   <li>Please let me know -- or patch the tutorial -- if I forgot something. I hate getting stuck on some finicky aspect of installation when I am trying to learn something.</li>
</ul>

<p><a href="/tutorial/run-tutorial-locally">Install me already!</a></p>


      

</ul>